image: unityci/editor:2022.3.11f1-base-0

stages:
  - test

unit_tests:
  stage: test
  script:
    - unity-editor -batchmode -nographics -projectPath . -runTests -testPlatform EditMode -logFile test-results.log
    - cat test-results.log
